### PR TITLE
Revert "CE-5643 TypeKit font: Proxima Nova Soft deprecated"

### PR DESCRIPTION
**Pull request by christopherlai**
Reverts CrazyEggInc/whisper-burner#1

### CODE REVIEW

**Comment by alexeygrinko-xo** [comment]
@christopherlai , @HatemHassan-xo , let's merge it, I need it for Shopify app

**Comment by christopherlai** [comment]
@alexeygrinko-xo this shouldn't be merged, we fixed this in another way.

**Comment by alexeygrinko-xo** [comment]
@christopherlai , ok, so I can use `$proxima-soft`?

**Comment by christopherlai** [comment]
@alexeygrinko-xo yup, just make sure you use tag v2.0.

**Pull request closed without merging**
